# App
fqdn: cluster.local
deployment_dir: "{{ ansible_env.HOME }}/deployment"
app_name: spring-boot-sample-hateoas
app_tag: v1
app_maintainer: gbava
app_maintainer_email: gaston.bava@email.cz
app_src_dir: "{{ deployment_dir }}/src/spring-boot/spring-boot-samples/spring-boot-sample-hateoas"
app_homedir: /tmp
app_port: 8080
app_service_port: 9000
app_log_volume: "/var/log/{{ app_name }}"

# Kubernetes
kube_version: v1.10.0
token: b0f7b8.8d1767876297d856
init_opts: "--apiserver-advertise-address 10.10.0.10"
kubeadm_opts: ""

service_subnet: 10.96.0
service_cidr: "{{ service_subnet }}.0/12"
dns_name: cluster.local
dns_ip: "{{ service_subnet }}.10"

# Kubernetes Network
network: flannel
pod_network_cidr: 10.244.0.0/16
cni_opts: "interface: eth1"

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf

# Maven
maven_version: 3.5.2
maven_destination_directory: /opt
maven_bin_url: http://apache.mirrors.spacedump.net/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
