FROM openjdk:8
MAINTAINER {{ app_maintainer_email }}
VOLUME /tmp
COPY {{ app_name }}.jar {{ app_homedir }}
ARG JAR_FILE
ADD ${JAR_FILE} {{ app_name }}.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","{{ app_homedir }}/{{ app_name }}.jar"]
EXPOSE {{ app_port }}
