---

- name: check that Docker is running
  service: name=docker state=started
  become: yes

- name: Log into DockerHub
  docker_login:
    username: "{{ app_maintainer }}"
    password: diScepol0
    email: "{{ app_maintainer_email }}"

- name: Copy Dockerfile template
  template: src=Dockerfile.j2 dest={{ deployment_dir }}/build/Dockerfile

- name: Build and push docker image to Docker Hub
  docker_image:
     path: "{{ deployment_dir }}/build"
     name: "{{ app_maintainer }}/{{ app_name }}"
     tag: "{{ app_tag }}"
     repository: "{{ app_maintainer }}/{{ app_name }}:{{ app_tag }}"
     buildargs:
       log_volume: "{{ app_log_volume }}"
       listen_port: "{{ app_port }}"
     push: yes
     force: yes
     state: present