- name: Enable privileged port range for nodePort
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: '- kube-apiserver'
    line: '    - --service-node-port-range=80-32767'
  become: yes
  register: reboot server

- name: reboot the server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  become: yes

- name: Wait for server come back
  wait_for: >
      host={{ inventory_hostname }}
      port=22
      delay=15
      timeout=60
  delegate_to: localhost