---
- name: Create directory for the app files
  file: path={{ deployment_dir }}/app state=directory

- name: Copy app-deployment.yaml file
  template: src=app-deployment.yaml.j2  dest={{ deployment_dir }}/app/app-deployment.yaml

- name: Copy app-service.yaml file
  template: src=app-service.yaml.j2  dest={{ deployment_dir }}/app/app-service.yaml

- name: Apply config files for deploying our app
  shell: kubectl apply -f {{ item }}
  with_items:
    - "{{ deployment_dir }}/app/app-deployment.yaml"
    - "{{ deployment_dir }}/app/app-service.yaml"