---

#- name: Upgrade all OS packages
#  yum:
#    name: '*'
#    state: latest

- name: Install ntp package
  yum: name=ntp state=installed
  notify: restart ntpd

- name: Install ntp package
  yum: name=ntp state=installed
  notify: restart ntpd

- name: Install subscription-manager package
  yum: name=subscription-manager state=installed

- name: Setup /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: Setup /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf